
# Site settings
title: Artificial Intelligence and Statistics Conference
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "/aistats1997" # the subpath of your site, e.g. /blog/
url: "http://www.aistats.org" # the base hostname & protocol for your site
#twitter_username: aistat
github_username:  aistats
author:
  name: AISTATS
  email:
comments: false
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: aistats

ghub:
  edit: true
  repository: aistats1997

banner: 

# Build settings
markdown: kramdown

conference:
  draft: false # set to True if the programme is draft only.
  image: 
  hide_tentative: true
  proceedings:
    url: 
    show: 
  room: 
  venue: Radisson Bahia Mar Beach Resort
  venue_url: 
  location: Ft. Lauderdale, FL, USA
  full_name: Artificial Intelligence and Statistics
  short_name: AISTATS
  name: Artificial Intelligence and Statistics
  year: 1997
  instance: 6th
  styling: International Workshop on
  dates:
  - 1997-01-04
  - 1997-01-07
  chairs:
  - type: General Chair
    people:
    - family: Smyth
      given: Padhraic
      institute: JPL and UCI
  - type: Program Chair
    people:
    - family: Madigan
      given: David
      institute: University of Washington
      url:

# change encoding for the generated output files to utf-8
encoding: utf-8


